---
root: true
plugins: [promise]
rules:
  # Hard to avoid in this project
  no-param-reassign: off
  # console is useful for CLI apps
  no-console: off
  # Avoid useless promise wrapping
  promise/no-return-wrap: error
  # Ensure consistent param names
  promise/param-names: error
  # Avoid swallowed exceptions
  promise/catch-or-return: error
env:
  es6: true
  node: true
extends: [airbnb-base]
